# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'Chevents' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  # Pods for Chevents

  target 'CheventsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CheventsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
